import = ["~/.config/alacritty/themes/themes/campbell.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 5
padding.y = 5
dynamic_padding = true

decorations = "Buttonless"
opacity = 0.8
blur = true

[font]
normal.family = "JetbrainsMono Nerd Font"
size = 14
