return {
  -- {
  --   "nvim-treesitter/nvim-treesitter",
  --   build = ":TSUpdate",
  --   lazy = false, -- ⚠️ загружается сразу
  --   opts = function(_, opts)
  --     opts.ensure_installed = opts.ensure_installed or {}
  --     vim.list_extend(opts.ensure_installed, { "blade", "php_only" })
  --   end,
  --   config = function(_, opts)
  --     vim.filetype.add({
  --       pattern = { [".*%.blade%.php"] = "blade" },
  --     })
  --
  --     pcall(function()
  --       local query = require("vim.treesitter.query")
  --       if query then
  --         query.set("vim", "highlights", "")
  --       end
  --     end)
  --
  --     local ok, configs = pcall(require, "nvim-treesitter.configs")
  --     if not ok then
  --       vim.notify("nvim-treesitter not found", vim.log.levels.WARN)
  --       return
  --     end
  --
  --     configs.setup(opts)
  --
  --     local parser_config = require("nvim-treesitter.parsers").get_parser_configs()
  --     parser_config.blade = {
  --       install_info = {
  --         url = "https://github.com/EmranMR/tree-sitter-blade",
  --         files = { "src/parser.c" },
  --         branch = "main",
  --         generate_requires_npm = false,
  --       },
  --       filetype = "blade",
  --     }
  --   end,
  -- },
  -- {
  --   "ricardoramirezr/blade-nav.nvim",
  --   dependencies = {
  --     "hrsh7th/nvim-cmp",
  --     "nvim-treesitter/nvim-treesitter",
  --   },
  --   ft = { "blade", "php" },
  -- },
}
